# Introduction to Python language

## Reusing code: script and modules

### Code snippet

In [1]:
msg = 'Hi, welcome to Euroscipy.'

msg.split()

['Hi,', 'welcome', 'to', 'Euroscipy.']

In [2]:
for word in msg.split():
    print(word)

Hi,
welcome
to
Euroscipy.


### import syntax

In [4]:
import numpy

numpy.random.random((2, 2))

array([[ 0.89206292,  0.30547085],
       [ 0.69904259,  0.80249916]])

In [5]:
import numpy as np

np.random.random((2, 2))

array([[ 0.54023251,  0.08341659],
       [ 0.78871764,  0.23014743]])

In [6]:
from numpy import random

random.random((2, 2))

array([[ 0.5735052 ,  0.27466014],
       [ 0.51056783,  0.53662014]])

In [7]:
from numpy.random import random as rnd_mat

rnd_mat((2, 2))

array([[ 0.95877073,  0.84074376],
       [ 0.13003586,  0.41873911]])